### ISSUE TITLE
Increase number of permutations in the test matrix

### ISSUE THREAD

**Issue by AlyssaCote** [CrayLabs/SmartDashboard#10]
# Description
The testing matrix needed to be reduced while the repo is private because we were being charged for the Gitlab minutes. Once SmartDashboard is made public, we need to revert back to what the test matrix was.

# Justification
We love tests!

# Implementation Strategy
In `.github/workflows/run_tests.yml`, matrix should be:
```
matrix:
        os: [macos-12, ubuntu-20.04] # Operating systems
        compiler: [8] # GNU compiler version
        py_v: [3.8, 3.9, '3.10'] # Python versions
```
